### ISSUE TITLE
云函数部署错误

### ISSUE THREAD

**Issue by aliyy2021** [icrons/ssp-sign#1]
大佬，你好，云函数部署出现如下错误，请问怎么解决？
![image](https://user-images.githubusercontent.com/77948441/116333208-a9159980-a805-11eb-9a8d-3a6d2868862f.png)

**Comment by icrons** [comment]
影响使用吗，不影响使用就不用管，影响使用的话给我看下具体的代码行数，应该是11行------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月28日(星期三) 上午9:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[icrons/ssp-sign] 云函数部署错误 (#1)

**Comment by aliyy2021** [comment]
不影响，出现网站无法访问或被墙

**Comment by icrons** [comment]
这个问题可能是机场官网国内ip段访问不了，换国外的部署一下就行了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月28日(星期三) 中午12:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [icrons/ssp-sign] 云函数部署错误 (#1)

**Comment by 953964771** [comment]
怎么没看地址
