### ISSUE TITLE
这是为什么

### ISSUE THREAD

**Issue by helloworld0816** [icrons/ssp-sign#2]
函数创建中...

函数创建失败, 失败原因：

未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by icrons** [comment]
参考https://www.52pojie.cn/thread-1268795-1-1.html进行配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "icrons/ssp-sign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上6:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[icrons/ssp-sign] 这是为什么 (#2)





 
函数创建中...
 
函数创建失败, 失败原因：
 
未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by helloworld0816** [comment]
> 参考[https://www.52pojie.cn/thread-1268795-1-1.html进行配置](https://www.52pojie.cn/thread-1268795-1-1.html%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "icrons/ssp-sign" ***@***.***&gt;; 发送时间:&nbsp;2021年4月29日(星期四) 晚上6:17 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[icrons/ssp-sign] 这是为什么 (#2) 函数创建中... 函数创建失败, 失败原因： 未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我直接运行main.py 可以签到成功，云函数部署失败

**Comment by helloworld0816** [comment]
{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"2fe3706d-edf5-4afc-b740-fb0cc45862d5","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 2, in main_handler\n    run = SspanelQd()\nNameError: name 'SspanelQd' is not defined","statusCode":430}
