### ISSUE TITLE
请问能否改为用cookie登录签到

### ISSUE THREAD

**Issue by Liujishou** [icrons/ssp-sign#3]
请问能否改为或添加用cookie登录签到，我在用的机场登录时添加了geetest的滑动验证，导致现在登录不了，我想用登录的cookie来实现登录签到不知道能否可行！

**Comment by icrons** [comment]
> 请问能否改为或添加用cookie登录签到，我在用的机场登录时添加了geetest的滑动验证，导致现在登录不了，我想用登录的cookie来实现登录签到不知道能否可行！

实现不了，抱歉
