### ISSUE TITLE
可以支持STAFF协议吗

### ISSUE THREAD

**Issue by ybmqya** [icrons/ssp-sign#4]
CopyRight ©2017-2019 几鸡-学习助理staff. All rights reserved.
网址https://j05.space/staff

**Comment by icrons** [comment]
> CopyRight ©2017-2019 几鸡-学习助理staff. All rights reserved.
> 网址https://j05.space/staff

可以
![屏幕截图 2021-07-31 082045.png](https://i.loli.net/2021/07/31/Do71kZAl2WgCf4b.png)
